# Generated by Django 4.2.1 on 2023-05-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_photo',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
