# Generated by Django 4.2.1 on 2023-05-28 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_profile_profile_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='tittle',
            new_name='title',
        ),
    ]
